version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: clinica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pudim666
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "sua url"
    ports:
      - "3000:3000"
    command: node dist/main.js
    volumes:
      - ./api:/app/api
      - /app/api/node_modules

volumes:
  postgres_data:
