version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: nest-api
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "3000:3000"
    command: node dist/main.js  # ou npm run start:prod
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: